/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Resource = {
  _type: "resource";
  type?: "Link" | "Repo" | "Article";
  title?: string;
  description?: string;
  url?: string;
};

export type Outcome = {
  _type: "outcome";
  icon?: "zap" | "layers" | "chart" | "focus";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<{
    _key: string;
  } & LessonReference>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<{
    _key: string;
  } & Resource>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level?: "Beginner" | "Intermediate" | "Advanced";
  price?: number;
  rating?: number;
  popular?: boolean;
  studentCount?: number;
  outcomes?: Array<{
    _key: string;
  } & Outcome>;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<{
    _key: string;
  } & Module>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Resource | Outcome | LessonReference | Module | SanityImageAssetReference | Lesson | SanityImageCrop | SanityImageHotspot | Slug | InstructorReference | CategoryReference | Course | Category | Instructor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    summary,    level,    price,    rating,    popular,    studentCount,    coverImage,    instructor->{ _id, name, expertise, "slug": slug.current },    category->{ _id, title, "slug": slug.current },    "lessonCount": count(modules[].lessons[]->_id)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  rating: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    expertise: string | null;
    slug: string | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  lessonCount: number | null;
}>;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] { "slug": slug.current }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: COURSE_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    level,    price,    rating,    popular,    studentCount,    coverImage,    outcomes[] { _key, icon, title, description },    instructor->{ _id, name, expertise, bio, "slug": slug.current, photo },    category->{ _id, title, "slug": slug.current },    modules[] {      _key,      title,      summary,      "lessons": lessons[]->{        _id,        title,        "slug": slug.current,        videoUrl,        duration,        freePreview,        studentCount,        poster,        keyPoints,        proTip,        resources[] { _key, type, title, description, url }      }    },    "lessonCount": count(modules[].lessons[]->_id)  }
export type COURSE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  price: number | null;
  rating: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  outcomes: Array<{
    _key: string;
    icon: "chart" | "focus" | "layers" | "zap" | null;
    title: string | null;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string | null;
    expertise: string | null;
    bio: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      videoUrl: string | null;
      duration: number | null;
      freePreview: boolean | null;
      studentCount: number | null;
      poster: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      keyPoints: Array<string> | null;
      proTip: string | null;
      resources: Array<{
        _key: string;
        type: "Article" | "Link" | "Repo" | null;
        title: string | null;
        description: string | null;
        url: string | null;
      }> | null;
    }> | null;
  }> | null;
  lessonCount: number | null;
} | null;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: COURSE_LESSON_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] {    "courseSlug": slug.current,    "lessonSlugs": modules[].lessons[]->slug.current  }
export type COURSE_LESSON_SLUGS_QUERY_RESULT = Array<{
  courseSlug: string | null;
  lessonSlugs: Array<string | null> | null;
}>;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: LESSON_BY_COURSE_QUERY
// Query: *[_type == "lesson" && slug.current == $lessonSlug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    duration,    freePreview,    studentCount,    poster,    notes,    keyPoints,    proTip,    resources[] { _key, type, title, description, url },    "course": *[_type == "course" && slug.current == $courseSlug && references(^._id)][0] {      _id,      title,      "slug": slug.current,      modules[] {        _key,        title,        summary,        "lessons": lessons[]->{          _id,          title,          "slug": slug.current,          duration,          freePreview        }      }    }  }
export type LESSON_BY_COURSE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  videoUrl: string | null;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "Article" | "Link" | "Repo" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    modules: Array<{
      _key: string;
      title: string | null;
      summary: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: string | null;
        duration: number | null;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] { "slug": slug.current }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    expertise,    bio,    photo,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  expertise: string | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  courseCount: number;
}>;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    expertise,    bio,    photo,    "courses": *[_type == "course" && references(^._id)] | order(_createdAt desc) {      _id,      title,      "slug": slug.current,      summary,      level,      price,      rating,      popular,      studentCount,      coverImage,      "lessonCount": count(modules[].lessons[]->_id)    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  expertise: string | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    level: "Advanced" | "Beginner" | "Intermediate" | null;
    price: number | null;
    rating: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    lessonCount: number | null;
  }>;
} | null;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] { "slug": slug.current }
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../my-app/sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  courseCount: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"course\" && defined(slug.current)] | order(_createdAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    summary,\n    level,\n    price,\n    rating,\n    popular,\n    studentCount,\n    coverImage,\n    instructor->{ _id, name, expertise, \"slug\": slug.current },\n    category->{ _id, title, \"slug\": slug.current },\n    \"lessonCount\": count(modules[].lessons[]->_id)\n  }\n": COURSES_QUERY_RESULT;
    "\n  *[_type == \"course\" && defined(slug.current)] { \"slug\": slug.current }\n": COURSE_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"course\" && slug.current == $slug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    summary,\n    level,\n    price,\n    rating,\n    popular,\n    studentCount,\n    coverImage,\n    outcomes[] { _key, icon, title, description },\n    instructor->{ _id, name, expertise, bio, \"slug\": slug.current, photo },\n    category->{ _id, title, \"slug\": slug.current },\n    modules[] {\n      _key,\n      title,\n      summary,\n      \"lessons\": lessons[]->{\n        _id,\n        title,\n        \"slug\": slug.current,\n        videoUrl,\n        duration,\n        freePreview,\n        studentCount,\n        poster,\n        keyPoints,\n        proTip,\n        resources[] { _key, type, title, description, url }\n      }\n    },\n    \"lessonCount\": count(modules[].lessons[]->_id)\n  }\n": COURSE_QUERY_RESULT;
    "\n  *[_type == \"course\" && defined(slug.current)] {\n    \"courseSlug\": slug.current,\n    \"lessonSlugs\": modules[].lessons[]->slug.current\n  }\n": COURSE_LESSON_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"lesson\" && slug.current == $lessonSlug][0] {\n    _id,\n    title,\n    \"slug\": slug.current,\n    videoUrl,\n    duration,\n    freePreview,\n    studentCount,\n    poster,\n    notes,\n    keyPoints,\n    proTip,\n    resources[] { _key, type, title, description, url },\n    \"course\": *[_type == \"course\" && slug.current == $courseSlug && references(^._id)][0] {\n      _id,\n      title,\n      \"slug\": slug.current,\n      modules[] {\n        _key,\n        title,\n        summary,\n        \"lessons\": lessons[]->{\n          _id,\n          title,\n          \"slug\": slug.current,\n          duration,\n          freePreview\n        }\n      }\n    }\n  }\n": LESSON_BY_COURSE_QUERY_RESULT;
    "\n  *[_type == \"lesson\" && defined(slug.current)] { \"slug\": slug.current }\n": LESSON_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    bio,\n    photo,\n    \"courseCount\": count(*[_type == \"course\" && references(^._id)])\n  }\n": INSTRUCTORS_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && slug.current == $slug][0] {\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    bio,\n    photo,\n    \"courses\": *[_type == \"course\" && references(^._id)] | order(_createdAt desc) {\n      _id,\n      title,\n      \"slug\": slug.current,\n      summary,\n      level,\n      price,\n      rating,\n      popular,\n      studentCount,\n      coverImage,\n      \"lessonCount\": count(modules[].lessons[]->_id)\n    }\n  }\n": INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && defined(slug.current)] { \"slug\": slug.current }\n": INSTRUCTOR_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"category\" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"courseCount\": count(*[_type == \"course\" && references(^._id)])\n  }\n": CATEGORIES_QUERY_RESULT;
  }
}

